# Generated by Django 4.1.4 on 2022-12-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_status', models.CharField(max_length=200)),
                ('event_location', models.CharField(max_length=200)),
            ],
        ),
    ]
