# Generated by Django 4.1.4 on 2022-12-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsapp', '0004_superusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
